name: Linter

on: [push]

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Checkout
        uses: actions/checkout@master
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
